# Definition of the environment variable keys
BATTERY_LEVEL = 'BATTERY_LEVEL'
CHARGING = 'CHARGING'
DUSTY_SPOT_SENSOR = 'DUSTY_SPOT_SENSOR'
GENERAL_CLEANING = 'GENERAL_CLEANING'
HOME_PATH = 'HOME_PATH'
SPOT_CLEANING = 'SPOT_CLEANING'
DUSTY_SPOT_PROBABILITY = 25
CLEAN_FLOOR_PROBABILITY = 10
BATTERY_LEVEL_START = 50
CLEAN_FLOOR = 'CLEAN_FLOOR'

